version: '3.8'

services:
  frontend:
    image: mariacarrero/fitlife-frontend:latest
    container_name: fitlife-frontend
    ports:
      - "80:80"
    environment:
      - API_GATEWAY_URL=http://52.1.222.152
    restart: always

