server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Configuración del Proxy hacia el Gateway de Microservicios
    location /api/ {
        # Usamos la IP privada de tu EC2 Backend para comunicación interna rápida y segura
        proxy_pass http://10.0.29.16:8080;
        
        # Cabeceras necesarias para que los microservicios reconozcan el tráfico original
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Evita problemas de timeout si los microservicios tardan un poco en responder
        proxy_connect_timeout 90s;
        proxy_read_timeout 90s;
    }

    # Optimización de rendimiento (Gzip)
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}